package ch.opentrainingcenter.transfer.impl;

// Generated 04.04.2013 20:38:06 by Hibernate Tools 3.4.0.CR1

import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import ch.opentrainingcenter.transfer.IAthlete;
import ch.opentrainingcenter.transfer.IHealth;
import ch.opentrainingcenter.transfer.IPlanungWoche;
import ch.opentrainingcenter.transfer.IRoute;
import ch.opentrainingcenter.transfer.ITraining;

/**
 * Athlete generated by hbm2java
 */
public class Athlete implements java.io.Serializable, IAthlete {
    private static final long serialVersionUID = 1L;
    private int id;
    private String name;
    private Date birthday;
    private Integer maxheartrate;
    private Set<IRoute> routes = new HashSet<>(0);
    private Set<IHealth> healths = new HashSet<>(0);
    private Set<ITraining> trainings = new HashSet<>(0);
    private Set<IPlanungWoche> planungwoches = new HashSet<>(0);

    public Athlete() {
    }

    public Athlete(final String name, final Date birthday, final Integer maxHeartBeat) {
        this.name = name;
        this.birthday = birthday;
        maxheartrate = maxHeartBeat;
    }

    @Override
    public int getId() {
        return this.id;
    }

    @Override
    public void setId(final int id) {
        this.id = id;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(final String name) {
        this.name = name;
    }

    @Override
    public Date getBirthday() {
        return this.birthday;
    }

    @Override
    public void setBirthday(final Date birthday) {
        this.birthday = birthday;
    }

    public Integer getMaxheartrate() {
        return this.maxheartrate;
    }

    public void setMaxheartrate(final Integer maxheartrate) {
        this.maxheartrate = maxheartrate;
    }

    public Set<IRoute> getRoutes() {
        return this.routes;
    }

    public void setRoutes(final Set<IRoute> routes) {
        this.routes = routes;
    }

    public Set<IPlanungWoche> getPlanungwoches() {
        return this.planungwoches;
    }

    public void setPlanungwoches(final Set<IPlanungWoche> planungwoches) {
        this.planungwoches = planungwoches;
    }

    @Override
    public void addTraining(final ITraining record) {
        trainings.add(record);
    }

    @Override
    public Integer getMaxHeartRate() {
        return maxheartrate;
    }

    @Override
    public void setMaxHeartRate(final Integer maxHeartRate) {
        maxheartrate = maxHeartRate;

    }

    @Override
    public Set<IHealth> getHealths() {
        return healths;
    }

    @Override
    public void setHealths(final Set<IHealth> healths) {
        this.healths = healths;
    }

    @Override
    public Set<ITraining> getTrainings() {
        return Collections.emptySet();
    }

    @Override
    public void setTrainings(final Set<ITraining> trainings) {
        this.trainings = trainings;

    }

    @SuppressWarnings("nls")
    @Override
    public String toString() {
        return "Athlete [id=" + id + ", name=" + name + ", birthday=" + birthday + ", maxheartrate=" + maxheartrate + "]";
    }
}
