package ch.opentrainingcenter.transfer.impl;

import ch.opentrainingcenter.transfer.IAthlete;
import ch.opentrainingcenter.transfer.IPlanungWoche;

// Generated 04.04.2013 20:38:06 by Hibernate Tools 3.4.0.CR1

/**
 * Planungwoche generated by hbm2java
 */
public class Planungwoche implements java.io.Serializable, IPlanungWoche {

    private static final long serialVersionUID = 1L;
    private int id;
    private IAthlete athlete;
    private Integer kw;
    private Integer jahr;
    private Integer kmprowoche;
    private Boolean interval;
    private Integer langerLauf;

    public Planungwoche() {
    }

    public Planungwoche(final IAthlete athlete, final Integer jahr, final Integer kw, final int kmprowoche, final Boolean interval, final Integer langerlauf) {
        this.athlete = athlete;
        this.kw = kw;
        this.jahr = jahr;
        this.kmprowoche = kmprowoche;
        this.interval = interval;
        this.langerLauf = langerlauf;
    }

    @Override
    public int getId() {
        return this.id;
    }

    @Override
    public void setId(final int id) {
        this.id = id;
    }

    @Override
    public IAthlete getAthlete() {
        return this.athlete;
    }

    @Override
    public void setAthlete(final IAthlete athlete) {
        this.athlete = athlete;
    }

    @Override
    public int getKw() {
        return this.kw;
    }

    public void setKw(final Integer kw) {
        this.kw = kw;
    }

    @Override
    public int getJahr() {
        return this.jahr;
    }

    public void setJahr(final Integer jahr) {
        this.jahr = jahr;
    }

    public Integer getKmprowoche() {
        return this.kmprowoche;
    }

    public void setKmprowoche(final Integer kmprowoche) {
        this.kmprowoche = kmprowoche;
    }

    public Boolean getInterval() {
        return this.interval;
    }

    public void setInterval(final Boolean interval) {
        this.interval = interval;
    }

    public Integer getLangerlauf() {
        return this.langerLauf;
    }

    public void setLangerlauf(final Integer langerlauf) {
        this.langerLauf = langerlauf;
    }

    @Override
    public void setKw(final int kw) {
        this.kw = kw;
    }

    @Override
    public void setJahr(final int jahr) {
        this.jahr = jahr;

    }

    @Override
    public int getKmProWoche() {
        return kmprowoche;
    }

    @Override
    public void setKmProWoche(final int kmProWoche) {
        kmprowoche = kmProWoche;
    }

    @Override
    public boolean isInterval() {
        return interval;
    }

    @Override
    public void setInterval(final boolean interval) {
        this.interval = interval;

    }

    @Override
    public int getLangerLauf() {
        return langerLauf;
    }

    @Override
    public void setLangerLauf(final int langerLauf) {
        this.langerLauf = langerLauf;
    }

}
