package ch.opentrainingcenter.transfer.impl;

import ch.opentrainingcenter.transfer.IStreckenPunkt;

// Generated 04.04.2013 20:38:06 by Hibernate Tools 3.4.0.CR1

/**
 * Streckenpunkte generated by hbm2java
 */
public class Streckenpunkte implements java.io.Serializable, IStreckenPunkt {

    private static final long serialVersionUID = 1L;
    private int id;
    private Double longitude;
    private Double latitude;

    public Streckenpunkte() {
    }

    public Streckenpunkte(final Double longitude, final Double latitude) {
        this.longitude = longitude;
        this.latitude = latitude;
    }

    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    @Override
    public double getLongitude() {
        return this.longitude;
    }

    @Override
    public void setLongitude(final double longitude) {
        this.longitude = longitude;
    }

    @Override
    public double getLatitude() {
        return this.latitude;
    }

    @Override
    public void setLatitude(final double latitude) {
        this.latitude = latitude;
    }

    @SuppressWarnings("nls")
    @Override
    public String toString() {
        return "Streckenpunkte [longitude=" + longitude + ", latitude=" + latitude + "]";
    }
}
