package ch.opentrainingcenter.transfer.impl;

// Generated 04.04.2013 20:38:06 by Hibernate Tools 3.4.0.CR1

import ch.opentrainingcenter.transfer.IWeather;

/**
 * Weather generated by hbm2java
 */
public class Weather implements java.io.Serializable, IWeather {

    private static final long serialVersionUID = 1L;
    private int id;
    private String wetter;
    private String imageicon;

    public Weather() {
    }

    public Weather(final int id) {
        this.id = id;
    }

    @Override
    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    @Override
    public String getWetter() {
        return this.wetter;
    }

    public void setWetter(final String wetter) {
        this.wetter = wetter;
    }

    public String getImageicon() {
        return this.imageicon;
    }

    public void setImageicon(final String imageicon) {
        this.imageicon = imageicon;
    }

    @SuppressWarnings("nls")
    @Override
    public String toString() {
        return "Weather [wetter=" + wetter + ", imageicon=" + imageicon + "]";
    }
}
